name: Sync from personal repo

on:
  workflow_dispatch:
  schedule:
    - cron: "*/59 * * * *"  # runs every 59 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout org repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "repo-sync-bot"
          git config user.email "repo-sync-bot@users.noreply.github.com"

      - name: Add personal repo and fetch
        run: |
          git remote add upstream https://github.com/Sanduni-P/shell-novice.git
          git fetch upstream --prune --tags

      - name: Fast-forward main branch
        run: |
          git checkout main
          git merge --ff-only upstream/main
          git push https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/PMacDaSci/shell-novice.git main

      - name: Sync tags
        run: |
          git push https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/PMacDaSci/shell-novice.git --tags
